// <auto-generated />
using Evoflare.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Evoflare.API.Migrations
{
    [DbContext(typeof(TechnicalEvaluationContext))]
    [Migration("20190218154459_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Evoflare.API.Models.Competence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.ToTable("Competence");
                });

            modelBuilder.Entity("Evoflare.API.Models.CompetenceLevel", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("CompetenceId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Description");

                    b.Property<int>("Level");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceId");

                    b.ToTable("CompetenceLevel");
                });

            modelBuilder.Entity("Evoflare.API.Models.Role", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("RoleId");

                    b.Property<string>("Summary");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Evoflare.API.Models.CompetenceLevel", b =>
                {
                    b.HasOne("Evoflare.API.Models.Competence", "Competence")
                        .WithMany("CompetenceLevel")
                        .HasForeignKey("CompetenceId")
                        .HasConstraintName("FK_CompetenceLevel_Competence");
                });
#pragma warning restore 612, 618
        }
    }
}
