FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build

WORKDIR /sources

COPY . .

RUN dotnet restore
RUN dotnet publish --configuration Release --output /app/

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app

COPY --from=build /app .

#COPY --from=localhost:50000/web:latest /app/dist ./wwwroot
 
CMD ASPNETCORE_ENVIRONMENT=Docker ASPNETCORE_URLS=http://*:$PORT dotnet Evoflare.API.dll