DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

GRANT ALL ON SCHEMA public TO public;

DROP SCHEMA IF EXISTS security CASCADE;
CREATE SCHEMA security;

DROP SCHEMA IF EXISTS core CASCADE;
CREATE SCHEMA core;
